---
- name: Include "{{cloud}}" variables
  include_vars:
    file: "{{cloud}}.yml"

- name: Download and unarchive storm files
  become: yes
  unarchive:
    src: "{{storm_mirror}}"
    dest: /home/{{user}}/
    remote_src: True

- name: Create storm yaml file
  become: yes
  template:
    src: storm.yaml.j2
    dest: /home/{{user}}/apache-storm-{{storm_version}}/conf/storm.yaml

- name: Create nimbus supervisor config file
  become: yes
  template:
    src: nimbus.conf.j2
    dest: /etc/supervisor/conf.d/nimbus.conf
  notify:
    - Restart supervisor
    - Restart nimbus

- name: Create ui supervisor config file
  become: yes
  template:
    src: ui.conf.j2
    dest: /etc/supervisor/conf.d/ui.conf
  notify:
    - Restart supervisor
    - Restart ui
