---
- hosts: cluster
  become: True
  vars_files:
   - "../vars/{{cloud}}.yml"
  tasks:
   - name: Update vms
     apt:
       update_cache: yes
   
   - name: Install required packages
     apt:
       name: "{{ item }}"
       state: latest
       install_recommends: no
     with_items:
        - openjdk-7-jre
        - openjdk-7-jdk
        - maven
        - supervisor
   
   - name: Create zookeeper, storm and supervisor directories
     file:
       path: /home/{{user}}/{{item}}
       state: directory
       mode: "a+rwx"
     with_items:
        - zookeeper-3.4.10/data
        - zookeeper-3.4.10/logs
        - apache-storm-1.1.0
        - supervisor/logs
   
   - name: Download and unarchive zookeeper files
     unarchive:
       src: http://www-us.apache.org/dist/zookeeper/stable/zookeeper-3.4.10.tar.gz
       dest: /home/{{user}}/
       remote_src: True
   
   - name: Download and unarchive storm files
     unarchive:
       src: http://www-us.apache.org/dist/storm/apache-storm-1.1.0/apache-storm-1.1.0.tar.gz
       dest: /home/{{user}}/
       remote_src: True
   
   - name: Update hosts file
     template:
       src: ../templates/hosts.j2
       dest: /etc/hosts
   
   - name: Create myid file for zookeeper config
     template:
       src: ../templates/myid.j2
       dest: /home/{{user}}/zookeeper-3.4.10/data/myid
   
   - name: Create zookeeper config file
     template:
       src: ../templates/zoo.cfg.j2
       dest: /home/{{user}}/zookeeper-3.4.10/conf/zoo.cfg
   
   - name: Create storm yaml config file
     template:
       src: ../templates/storm.yaml.j2
       dest: /home/{{user}}/apache-storm-1.1.0/conf/storm.yaml

- hosts: nimbus
  become: True
  vars_files:
   - "../vars/{{cloud}}.yml"
  tasks:
   - name: Create nimbus supervisor config file
     template:
       src: ../templates/nimbus.conf.j2
       dest: /etc/supervisor/conf.d/nimbus.conf
   - name: Create ui supervisor config file
     template:
       src: ../templates/ui.conf.j2
       dest: /etc/supervisor/conf.d/ui.conf

- hosts: supervisors
  become: True
  vars_files:
   - "../vars/{{cloud}}.yml"
  tasks:
   - name: Create supervisor supervisor config file
     template:
       src: ../templates/worker.conf.j2
       dest: /etc/supervisor/conf.d/worker.conf
