---
- hosts: nimbus
  become: True
  vars_files:
   - "../vars/{{cloud}}.yml"
  tasks:
   - name: Copy jar to nimbus
     command: service supervisor restart
   - name: Load nimbus and ui conf files
     command: supervisorctl reread
   - name: Ensure supervisor is updated
     command: supervisorctl update
   - name: Start storm nimbus
     command: supervisorctl start nimbus
   - name: Start storm ui
     command: supervisorctl start ui
